version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - $CACHE_VERSION-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        key: $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm run format

  back-test-unit:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
      - run: npm run test

  back-test-e2e:
    docker:
      - image: circleci/node:dubnium-browsers
      - image: circleci/postgres:9.6.5
        environment:
          POSTGRES_DB: db
          POSTGRES_USER: typeormtest
          POSTGRES_PASSWORD: password
          working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
      - run: npm run test:e2e

  docker-build-and-push:
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag app $DOCKER_HUB_USER_ID/auto-pres-check-api:$CIRCLE_BUILD_NUM
            docker tag app $DOCKER_HUB_USER_ID/auto-pres-check-api:latest
            docker push $DOCKER_HUB_USER_ID/auto-pres-check-api:$CIRCLE_BUILD_NUM
            docker push $DOCKER_HUB_USER_ID/auto-pres-check-api:latest
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - back-test-unit:
          requires:
            - build
      - back-test-e2e:
          requires:
            - build
      - lint:
          requires:
            - build
      - docker-build-and-push:
          requires:
            - build
            - lint
            - back-test-e2e
            - back-test-unit
